### ISSUE TITLE
Update and add more exercises to format.md episode 

### ISSUE THREAD

**Issue by SarahAlidoost** [esciencecenter-digital-skills/Lesson-FAIR-Data-Climate#22]
Add two types of exercises in this episode:
- ask the learner to search for a common format (mentioned in this episode) in https://fairsharing.org/ and inspect the result.
- ask the learner to have a look at the checklist https://zenodo.org/record/3405141#.X4AeiHUzZhF and find those that are related to the file format.

Consider CF convention for CMIP data that is related to NetCDF format as an example. For other climate-related domains, add any conventions/standards that are related to a specific format.
Some resources: 
https://gmd.copernicus.org/articles/11/3659/2018/gmd-11-3659-2018.pdf
https://cfconventions.org/index.html
https://pcmdi.llnl.gov/CMIP6/Guide/dataUsers.html

Also, polish the exercises and lessons to illustrate clearly about common/ acceptable/ recommended formats.

**Comment by Peter9192** [comment]
Just an idea: Instead of searching for and adding conventions from all conceivable climate-related fields (we'll probably never manage to be complete/exhaustive), we could also make an exercise out of it for the learners. We could also build up knowledge over time as we're teaching this lesson and getting feedback from the participants.
